src/Entity/Car.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity]
#[ORM\Table(name: 'cars')]
class Car
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Avto = null;

    #[ORM\Column]
    private ?int $price = null;
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAvto(): ?string
    {
        return $this->Avto;
    }

    public function setAvto(string $Avto): static
    {
        $this->Avto = $Avto;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }
}

templates/avg.html.twig
<table>
    <thead>
      <tr>
        <th>summ</th>
      </tr>
    </thead>
    <tbody>
      {% for order in orders %}
      <tr>
          <td>{{order.average_purchase_amount}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>>

templates/gold.html.twig
<table>
    <thead>
      <tr>
        <th>summ</th>
        <th>nazvanie</th>
      </tr>
    </thead>
    <tbody>
      {% for order in orders %}
      <tr>
          <td>{{orders.price}}</td>
          <td>{{orders.avto}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>>

templates/list.html.twig
<html>
<body>
<h2>Список клиентов и число их покупок</h2>
<form method="post" action="{{ path('list') }}">
<input type="submit" value="отправить">
<table>
    <thead>
        <tr>
            <th>Имя</th>
            <th>Почта</th>
            <th>Количество заказов</th>
        </tr>
    </thead>
    <tbody>
        {% for people in peoples %}
            <tr>
                <td>{{ people.name }}</td>
                <td>{{ people.email }}</td>
                <td>{{ people.Quantity }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="2">Нет данных.</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
</body>
</html>

templates/top.html.twig
<table>
    <thead>
      <tr>
        <th>summa</th>
        <th>name</th>
      </tr>
    </thead>
    <tbody>
      {% for order in orders %}
      <tr>
          <td>{{orders.total_spent}}</td>
          <td>{{orders.name}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>>

templates/total.html.twig
<table>
    <thead>
      <tr>
        <th>summ</th>
        <th>name</th>
      </tr>
    </thead>
    <tbody>
      {% for order in orders %}
      <tr>
          <td>{{order.totalAmount}}</td>
          <td>{{order.name}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>>